name: Check CSS formatting

on:
    push:
        branches:
            - main
        paths:
            - "styles/**/*"
            - "**/*.js"
    pull_request:
        paths:
            - "styles/**/*"
            - "**/*.js"

jobs:
    prettier:
        name: Prettier CSS check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Check CSS formatting
              run: bun run format:check
